##############################################
#                                            #
#                Dracula Theme               #
#                                            #
##############################################

# This theme was created by: https://github.com/BeanieBarrow ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "dracula"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#f8f8f2"
full_screen_bg = "none"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#50fa7b", "#ff5555"]

#-- File Panel
file_panel_fg = "#f8f8f2"
file_panel_bg = "none"
file_panel_border = "#6272a4"
file_panel_border_active = "#ff79c6"
file_panel_top_directory_icon = "#50fa7b"
file_panel_top_path = "#8be9fd"
file_panel_item_selected_fg = "#ffb86c"
file_panel_item_selected_bg = "#282a36"

#-- Footer
footer_fg = "#f8f8f2"
footer_bg = "none"
footer_border = "#6272a4"
footer_border_active = "#ff79c6"

#-- Sidebar
sidebar_fg = "#f8f8f2"
sidebar_bg = "none"
sidebar_title = "#bd93f9"
sidebar_border = "#282a36"
sidebar_border_active = "#ff79c6"
sidebar_item_selected_fg = "#ffb86c"
sidebar_item_selected_bg = "#282a36"
sidebar_divider = "#868686"

#-- Modals
modal_fg = "#f8f8f2"
modal_bg = "none"
modal_border_active = "#ff79c6"
modal_cancel_fg = "#f8f8f2"
modal_cancel_bg = "#6272a4"
modal_confirm_fg = "#f8f8f2"
modal_confirm_bg = "#ffb86c"

#-- Help Menu
help_menu_hotkey = "#09090d"
help_menu_title = "#bd93f9"

#-- Special
cursor = "#ff79c6"
correct = "#50fa7b"
error = "#ff5555"
hint = "#8be9fd"
cancel = "#6272a4"
